version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: pod_demo
      POSTGRES_PASSWORD: YXJoRv7eIujMwmjPZEb53Y9Ap57KephS
    volumes:
      - pod_demo_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass iyRsmJdwWJJ4EKNaMP2cy76gfghL4bj3
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  pod_demo_data:
