#!/bin/sh

# Start docker
echo "Starting docker"
docker-compose up --build --detach

while ! netstat -tna | grep 'LISTEN' | grep -q '.8090'; do
  echo "Waiting for Postgres..."
  sleep 2 # time in seconds, tune it as needed
done

sleep 2

echo "Postgres is ready"

docker-compose run postgres env PGPASSWORD="YXJoRv7eIujMwmjPZEb53Y9Ap57KephS" psql -h postgres -U postgres -d pod_demo < generated/tables-serverpod.pgsql

echo "Stopping docker"
docker-compose stop
